image: scratch

stages:
  - build
  - package
  - deploy

build-jar:
  image: bellsoft/liberica-openjdk-alpine:14
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
  interruptible: true
  retry: 1
  only:
    - master

build-native-image:
  image: bellsoft/liberica-openjdk-debian:14
  stage: build
  before_script:
    - chmod +x gradlew
    - apt-get update -qq
    - apt-get install -y -qq build-essential libz-dev zlib1g-dev
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/graal/
  interruptible: true
  retry: 1
  only:
    - master
