image: scratch

stages:
  - build
  - deploy

build-jar:
  image: bellsoft/liberica-openjdk-alpine:15
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
  interruptible: true
  retry: 1
  only:
    - master

heroku-deploy:
  image: docker
  stage: deploy
  when: manual
  services:
    - docker:dind
  before_script:
    - apk add --update curl
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - imageId=$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})
    - |
      curl -f -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
        -H "Authorization: Bearer $HEROKU_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        -d "{\"updates\":[{\"type\":\"web\",\"docker_image\":\"$imageId\"}]}"
