image: scratch

stages:
  - build
  - deploy

build-jar:
  image: bellsoft/liberica-openjdk-alpine:15
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
  interruptible: true
  retry: 1
  only:
    - master

heroku-deploy:
  image: docker
  stage: deploy
  when: manual
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt-get install curl gnupg2 -y
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - heroku container:push web -a $HEROKU_APP_NAME
    - heroku container:release web -a $HEROKU_APP_NAME
