name: Build

on:
  push:
    branches:
      - master

jobs:
  build-jar:
    name: Build Jar
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/*.jar
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-jar
    defaults:
      run:
        working-directory: .
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: jar
          path: build/libs
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/denyshorman/wstunnel:latest
