name: Build Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs checkout
      - run: chmod +x ./gradlew && ./gradlew shadowJar
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/denyshorman/wstunnel:latest
          cache-from: type=registry,ref=ghcr.io/denyshorman/wstunnel:buildcache
          cache-to: type=registry,ref=ghcr.io/denyshorman/wstunnel:buildcache,mode=max
